[general]
import = [
    "~/.config/alacritty/fonts.toml",
]
live_config_reload = true

[cursor]
blink_interval = 530
unfocused_hollow = true
thickness = 0.15

[cursor.style]
blinking = "On"
shape = "Block"

[selection]
save_to_clipboard = true

[window]
decorations = "none"
dynamic_title = true
opacity = 0.75
dynamic_padding = true

[window.padding]
x = 15
y = 12

[scrolling]
history = 10000
multiplier = 3
