# rosepine palette

# base = #191724
# surface = #1f1d2e
# overlay = #26233a
# muted = #6e6a86
# subtle = #908caa
# text = #e0def4
# love = #eb6f92
# rose = #ebbcba
# gold = #f6c177
# iris = #c4a7e7
# pine = #31748f
# foam = #9ccfd8
# highlight_low = #21202e
# highlight_mid = #403d52
#highlight_high = #524f67

[mgr]

border_symbol = " "
border_style  = { fg = "#191724" }
