[mgr]
cwd = { fg = "#ebbcba" }

border_style  = { fg = "#524f67" }

hovered = { bg = "#21202e" }

find_keyword = { fg = "#f6c177", italic = true }
find_position = { fg = "#eb6f92", bg = "reset", italic = true }

marker_selected = { fg = "#9ccfd8", bg = "#9ccfd8" }
marker_copied = { fg = "#f6c177", bg = "#f6c177" }
marker_cut = { fg = "#eb6f92", bg = "#eb6f92" }
marker_marked = { fg = "#c4a7e7", bg = "#c4a7e7" }

count_copied   = { fg = "#191724", bg = "#f6c177", bold = true }
count_cut      = { fg = "#e0def4", bg = "#eb6f92", bold = true }
count_selected = { fg = "#e0def4", bg = "#31748f" }


[spot]
border = { fg = "#26233a" }
title = { fg = "#f6c177" }

tbl_col  = { fg = "#9ccfd8" }
tbl_cell = { bg = "#21202e" }


[pick]
border   = { fg = "#524f67" }
active   = { fg = "#c4a7e7", bold = true }


[confirm]
border  = { fg = "#26233a" }
title   = { fg = "#f6c177" }
btn_yes = { fg = "#eb6f92" }
btn_no = { fg = "#31748f" }
btn_labels = [ "  [Y]es  ", "  (N)o  " ]


[mode]
normal_main = { fg = "#191724", bg = "#ea9a97", bold = true }
normal_alt  = { fg = "#191724", bg = "#ebbcba", bold = true }

select_main = { fg = "#191724", bg = "#c4a7e7", bold = true }
select_alt  = { fg = "#191724", bg = "#907aa9", bold = true }

unset_main = { fg = "#191724", bg = "#f6c177", bold = true }
unset_alt  = { fg = "#191724", bg = "#ea9d34", bold = true }


[status]
sep_left  = { open = "█", close = "" }
sep_right = { open = "", close = "█" }

mode_normal = { fg = "#191724", bg = "#ebbcba", bold = true }
mode_select = { fg = "#e0def4", bg = "#9ccfd8", bold = true }
mode_unset = { fg = "#e0def4", bg = "#b4637a", bold = true }

progress_label = { fg = "#e0def4", bold = true }
progress_normal = { fg = "#191724", bg = "#2A273F" }
progress_error = { fg = "#B4637A", bg = "#2A273F" }


[input]
border = { fg = "#26233a" }
title = { fg = "#f6c177" }
value = { fg = "#e0def4" }
selected = { reversed = true }


[help]
on = { fg = "#9ccfd8" }
exec = { fg = "#9ccfd8" }
desc = { fg = "#9399b2" }
hovered = { bg = "#21202e", bold = true }
footer = { fg = "#2A273F", bg = "#e0def4" }


[tabs]
active   = { fg = "#191724", bg = "#c4a7e7", bold = true }
inactive = { bg = "#1f1d2e", fg = "#c4a7e7" }


[tasks]
border = { fg = "#524f67" }
title = {}
hovered = { underline = true }


[filetype]
rules = [
	# Images
	{ mime = "image/*", fg = "#c4a7e7" },

	# Media
	{ mime = "{audio,video}/*", fg = "#c4a7e7" },

	# Archives
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#31748f" },

	# Documents
	{ mime = "application/{pdf,doc,rtf}", fg = "#9ccfd8" },

	# Empty files
	{ mime = "inode/empty", fg = "#6e6a86" },

	# Special files
	{ name = "*", is = "orphan", bg = "#908caa" },
	{ name = "*", is = "exec"  , fg = "#ebbcba" },

	# Dummy files
	{ name = "*", is = "dummy", bg = "#ebbcba" },
	{ name = "*/", is = "dummy", bg = "#ebbcba" },

    # Symbolic links
    { name = "*", is = "link", fg = "#f6c177" },
    { name = "*/", is = "link", fg = "#f6c177" },

	# Fallback
	# { name = "*", fg = "white" },
	{ name = "*/", fg = "blue" }
]
