modmap: 
  - name: Swap Caps and Esc
    remap:
      CapsLock: Esc
      Esc: CapsLock
  
  - name: For tezarre
    remap: 
      SHIFT_R: SLASH
    device:
      only: ['RONGYUAN 2.4G Wireless', 'ROYUAN Gaming Keyboard']

keymap:
  - name: Arrow Key Remapping
    remap:
      Super-h: left
      Super-j: down
      Super-k: up
      Super-l: right
